version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net

  postgres-portcast:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - opensearch-net

  portcase:
    build: .
    environment:
      OPENSEARCH_HOST: https://opensearch:9200
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
      DEFAULT_ENTRY_PER_PAGE: 20
      PORT: 8000
      HOST: 0.0.0.0
      MIGRATION: True
      PG_HOST: postgres-portcast
      PG_PORT: 5432
      PG_DATABASE: mydatabase
      PG_USER: myuser
      PG_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    networks:
      - opensearch-net
    depends_on:
      - opensearch
      - postgres-portcast
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - opensearch-net

volumes:
  opensearch-data:
  postgres_data:

networks:
  opensearch-net: